### ISSUE TITLE
The program is crashing

### ISSUE THREAD

**Issue by ARandomDude420** [algb12/UDPGeolocate#4]
The program is crashing every time I start it. I installed the drivers and followed every step.
Please fix this issue.

**Comment by algb12** [comment]
Hi,

Thanks for your interest in UDPGeolocate.
This is just to let you know that this program isn't under active maintenance anymore, so many things probably changed.
I stopped maintaining this program due to both, less time on my hands, and changes implemented by Omegle to the protocol.
I will now close this issue - if I do have the time, I might get back to this.

Thanks for your understanding, and best wishes and stay safe,
Alex
